<a href="https://colab.research.google.com/github/007-007-oss/basic-stuff/blob/main/pandasbasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import pandas as pd

students_df = pd.DataFrame({
    'student_id': [1, 2, 3, 4],
    'name': ['Aman', 'Priya', 'Rahul', 'Anjali'],
    'city': ['Delhi', 'Mumbai', 'Delhi', 'Pune']
})

activity_df = pd.DataFrame({
    'student_id': [1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4],
    'day': [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
    'minutes_watched': [30, 45, 20, 60, 55, 70, 15, 25, 40, 50, 0, 35]
})

In [ ]:
students_df

   student_id    name    city
0           1    Aman   Delhi
1           2   Priya  Mumbai
2           3   Rahul   Delhi
3           4  Anjali    Pune

In [ ]:
pd.merge(students_df, activity_df)

    student_id    name    city  day  minutes_watched
0            1    Aman   Delhi    1               30
1            1    Aman   Delhi    2               45
2            1    Aman   Delhi    3               20
3            2   Priya  Mumbai    1               60
4            2   Priya  Mumbai    2               55
5            2   Priya  Mumbai    3               70
6            3   Rahul   Delhi    1               15
7            3   Rahul   Delhi    2               25
8            3   Rahul   Delhi    3               40
9            4  Anjali    Pune    1               50
10           4  Anjali    Pune    2                0
11           4  Anjali    Pune    3               35

In [ ]:
students_df = students_df[students_df["city"] == "Delhi"]
students_df

   student_id   name   city
0           1   Aman  Delhi
2           3  Rahul  Delhi